### ISSUE TITLE
NextCloud: Apps page not loading

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#13]
1. I logged in as superuser and created a new acct (alexcg) with admin privileges
2. Logged in as alexcg
3. Went to settings -> apps
4. Just get animated spinner telling me something is loading, but nothing really loads

**Comment by yangboz** [comment]
I have tried to setup another  account yangboz, after loading a while, even though console thrown some errors: "DevTools failed to parse SourceMap: http://118.190.3.169:8000/core/vendor/purify.min.js.map" , but the dashboard show up.

**Comment by alexcg1** [comment]
Fixed, but leads to #15 , which is being fixed now. Closing this bug
