### ISSUE TITLE
Nextcloud: Can't install apps

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#15]
![image](https://user-images.githubusercontent.com/4182659/35853020-04d83e54-0b5f-11e8-9245-54d633e848fd.png)
I tried installing apps from http://go.toyhouse.cc:8080/settings/apps?category=app-bundles# but no luck. Likely because apps are hosted on Amazon AWS. When I ran Nextcloud/docker on my own machine in China I had exact same problem. Assume it's blocked by GFW.

Error: cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out

Logged in as superuser

**Comment by yangboz** [comment]
yes, that's the GFW related. Let's move to AWS.

**Comment by alexcg1** [comment]
Cool cool :) Should speed things up for any testers outside China too
