### ISSUE TITLE
Virtualbox image complains it can't find network adaptor eth0 (airport)

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#2]
Use case: Upon opening the ova file and attempting to boot. VM won't even start
Fix: Open settings and go to network page. It fixes itself

Since it's looking for airport, I'm assuming this img is from a Mac. Is there any way we can fix it so we don't get an error on either mac or pc regarding network adaptor?

**Comment by yangboz** [comment]
Yes, because this virtual box images file comes out from MacOSX.

**Comment by yangboz** [comment]
Let's Dind.
