### ISSUE TITLE
Virtualbox image download really slow

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#3]
It's taken me days to download the Virtualbox image file. I've been getting >200kbps speeds, I think because the server is in China and I'm not. This will affect MIT's usability of our software.

Tested on multiple wifi networks in Thailand, which deliver high speed otherwise.

Proposed fix: Mirror the image in USA

**Comment by yangboz** [comment]
Trying to host a nextCloud on AWS...

**Comment by yangboz** [comment]
Now we used AWS nextCloud: http://remix.cafe to fix it up.
