### ISSUE TITLE
Wishlist: Start microservices on boot

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#5]
Typing in commands manually seems error prone and maybe too technical for users who just want to test things. Can we start all the docker stuff  via /etc/init.d or some other way?

The commands I mean are:
`cd TensorCloud & docker-compose -f mariadb_mediawiki.yml -f wordpress.yml -f piwikyml -f phabricator.yml -f openmodelica-webbook.yml -f jenkins.yml up -d`
`/home/toyhouse/resourcespace-8.3.1/ctlscript.sh start`

**Comment by yangboz** [comment]
Yes, I have to try write down those command on Ubuntu's startup script.

**Comment by yangboz** [comment]
references:  

https://askubuntu.com/questions/9853/how-can-i-make-rc-local-run-on-startup

https://community.bitnami.com/t/execution-by-root-not-allowed/4711

**Comment by yangboz** [comment]
Now, [https://github.com/benkoo/TensorCloud/blob/master/ricomp.sh](https://github.com/benkoo/TensorCloud/blob/master/ricomp.sh) did the startup script support.
