### ISSUE TITLE
Security: All images have same user/password

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#8]
This is okay for testing, but if we roll out, then admin 1 can login to admin 2's image.

Suggestion: Prompt user to change password (for local login and SSH) upon first login

Suggested user-flow:
Boot -> auto-login -> change password program autostarts

**Comment by yangboz** [comment]
Because all of ENVs variables has been pre-defined on static docker-composed files, In this stage, it can not support  a dynamic way. :-(

**Comment by yangboz** [comment]
We are try to use a OAuthServer base on http://remix.network with OpenID connect providers.

**Comment by yangboz** [comment]
Let's Dind.
