### ISSUE TITLE
Virtualbox: Huge disk image

### ISSUE THREAD

**Issue by alexcg1** [benkoo/TensorCloud#9]
Can we strip out some of the default Ubuntu cruft? I mean do we really need Unity, X11, etc? We could just strip back to command line interface, or failing that, a really simple window manager and app launcher

This, coupled with mirror, could speed things up dramatically and reduce complexity

**Comment by yangboz** [comment]
Maybe we can use a Ubuntu server base image.

**Comment by yangboz** [comment]
I am try to use RancherOS based image...

**Comment by yangboz** [comment]
Now we trying use Docker in Docker to slim the virtualbox version.

**Comment by yangboz** [comment]
now, we changed to use docker in docker: https://github.com/benkoo/TensorCloud/tree/master/DockerInDocker
